version: '3.8'

services:
  ecowinds-db:
    image: postgres:latest
    container_name: postgres-ecowinds
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecowinds_db
    ports:
      - "5432:5432"
    volumes:
      - ecowinds_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ecowinds-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ecowinds_mqtt_data:/mosquitto/data
    restart: unless-stopped

  ecowinds-backend:
    build: .
    container_name: ecowinds-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://ecowinds-db:5432/ecowinds_db
      PGUSER: postgres
      PGPASSWORD: postgres
      MQTT_BROKER_URL: tcp://mosquitto:1883
      JWT_SECRET: minha_chave_secreta_super_segura_ecowinds_2026
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      ecowinds-db:
        condition: service_healthy
      mosquitto:
        condition: service_started
    restart: unless-stopped

volumes:
  ecowinds_pg_data:
  ecowinds_mqtt_data: