services:
  - type: web
    name: ecowinds-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://ep-patient-mountain-aquoe1ox-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: PGUSER
        value: neondb_owner
      - key: PGPASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:4200  # Atualize com a URL do frontend em produção
